TelegramBot 03-12 INFO: started TelegramBot
TelegramBot 03-12 INFO: Application started
TelegramBot 03-12 ERROR: No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/andres/coding/listapp2/venv/lib/python3.10/site-packages/telegram/ext/_application.py", line 1104, in process_update
    await coroutine
  File "/home/andres/coding/listapp2/venv/lib/python3.10/site-packages/telegram/ext/_handler.py", line 141, in handle_update
    return await self.callback(update, context)
  File "/home/andres/coding/listapp2/bot/tlbot.py", line 37, in echo_public
    text=bot_res
UnboundLocalError: local variable 'bot_res' referenced before assignment
TelegramBot 03-12 ERROR: No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/andres/coding/listapp2/venv/lib/python3.10/site-packages/telegram/ext/_application.py", line 1104, in process_update
    await coroutine
  File "/home/andres/coding/listapp2/venv/lib/python3.10/site-packages/telegram/ext/_handler.py", line 141, in handle_update
    return await self.callback(update, context)
  File "/home/andres/coding/listapp2/bot/tlbot.py", line 37, in echo_public
    text=bot_res
UnboundLocalError: local variable 'bot_res' referenced before assignment
TelegramBot 03-12 ERROR: No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/andres/coding/listapp2/venv/lib/python3.10/site-packages/telegram/ext/_application.py", line 1104, in process_update
    await coroutine
  File "/home/andres/coding/listapp2/venv/lib/python3.10/site-packages/telegram/ext/_handler.py", line 141, in handle_update
    return await self.callback(update, context)
  File "/home/andres/coding/listapp2/bot/tlbot.py", line 37, in echo_public
    text=bot_res
UnboundLocalError: local variable 'bot_res' referenced before assignment
TelegramBot 03-12 INFO: Application is stopping. This might take a moment.
TelegramBot 03-12 INFO: Application.stop() complete
TelegramBot 03-12 INFO: started TelegramBot
TelegramBot 03-12 INFO: Application started
TelegramBot 03-12 ERROR: No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/andres/coding/listapp2/venv/lib/python3.10/site-packages/telegram/ext/_application.py", line 1104, in process_update
    await coroutine
  File "/home/andres/coding/listapp2/venv/lib/python3.10/site-packages/telegram/ext/_handler.py", line 141, in handle_update
    return await self.callback(update, context)
  File "/home/andres/coding/listapp2/bot/tlbot.py", line 37, in echo_public
    text=bot_res
UnboundLocalError: local variable 'bot_res' referenced before assignment
